apiVersion: v1
kind: Pod

metadata:
  name: spring-pod
spec:
  containers:
  - name: spring-container
    image: spring-server
    ports:
    - containerPort: 8080
    imagePullPolicy: Never
    env:
      - name: SPIRNG_DATASOURCE_URL
        value: "jdbc:mariadb://mariadb:3306/commerce"
      - name: SPRING_DATASOURCE_USERNAME
        value: "root"
      - name: SPIRNG_DATASOURCE_PASSWORD
        value: "admin123" 
---
apiVersion: v1
kind: Pod

metadata:
  name: mariadb-pod
  labels:
    app: mariadb
spec:
  containers:
  - name: mariadb
    image: mariadb:10.6 
    env: 
    - name: MARIADB_DATABASE
      value: "commerce"
    - name: MARIADB_ROOT_PASSWORD
      value: "admin123"
    ports:
      - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
spec:
  selector:
    app: mariadb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306

