crds:
  enabled: true

grafana:
  adminPassword: admin1234
  service:
    type: ClusterIP
  additionalDataSources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki-gateway.logging.svc.cluster.local
      isDefault: false
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 384Mi

prometheus:
  enabled: true
  service:
    type: ClusterIP
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}
    ruleSelectorNilUsesHelmValues: false
    ruleSelector: {}
    ruleNamespaceSelector: {}
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi

alertmanager:
  enabled: true

  alertmanagerSpec:
    secrets:
      - alertmanager-slack-webhook
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 256Mi

  config:
    global:
      resolve_timeout: 5m

    route:
      receiver: slack-default
      group_by: ['alertname']
      group_wait: 10s
      group_interval: 1m
      repeat_interval: 1h

    receivers:
      - name: slack-default
        slack_configs:
          - api_url_file: /etc/alertmanager/secrets/alertmanager-slack-webhook/SLACK_WEBHOOK_URL
            channel: '#alerts'
            send_resolved: true
            title: "[{{ .Status | toUpper }}] {{ .CommonLabels.alertname }}"
            text: |
              summary: {{ .CommonAnnotations.summary }}
              description: {{ .CommonAnnotations.description }}
