architecture: standalone

auth:
  enabled: true
  password: "redis1234"
master:
  persistence:
    enabled: true
    size: 2Gi
metrics:
  enabled: true
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi
