spring:
    application:
        name: commerce

    datasource:
        url: jdbc:mariadb://mariadb:3306/commerce
        #url: jdbc:mariadb://localhost:3306/commerce
           #url: jdbc:mariadb://commerce-mariadb:3306/commerce
        username: root
        password: admin123
        driver-class-name: org.mariadb.jdbc.Driver

    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
              format-sql: true
              dialect: org.hibernate.dialect.MariaDBDialect

    cache:
      type: redis
      redis:
        time-to-live: 60s
        cache-null-values: false
    data:
      redis:
        host: redis-master #실제서비스이름으로 변경예정 kubectl get svc -n commerce
        port: 6379
        password: redis1234

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    health:
      show-details: always 
