{{- if .Values.mariadb.enabled }}

apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: mariadb
spec: 
  serviceName: mariadb
  replicas: {{ .Values.mariadb.replicaCount }}
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb 
        image: "{{ .Values.mariadb.image.repository }}{{if .Values.mariadb.image.tag}}:{{ .Values.mariadb.image.tag }}{{ end }}"
        env:
        - name: MARIADB_DATABASE
          value: {{ .Values.mariadb.env.datasource.database }}
        - name: MARIADB_ROOT_PASSWORD
          value: {{ .Values.mariadb.env.datasource.rootPassword }}
        ports:
          - containerPort: {{ .Values.mariadb.containerPort }}
        volumeMounts:
        - name: mariadb-data
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mariadb-data
    spec:
      accessModes: {{ .Values.mariadb.persistence.accessModes | toJson }}
      resources:
        requests:
          storage: {{ .Values.mariadb.persistence.size }}
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb #api-deploy의 url "jdbc:mariadb://mariadb:3306/commerce" 
spec:
  selector:
    app: mariadb
  ports:
    - protocol: {{ .Values.mariadb.service.protocol }}
      port: {{ .Values.mariadb.service.port }}
      targetPort: {{ .Values.mariadb.service.targetPort }}
 
{{- end }}
