apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: commerce-api-raw
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/euneun023/commerce.git
    targetRevision: feature/health-db-v2
    path: k8s

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: commerce

  syncPolicy:
    automated:
      prune: true #Git에 없는 리소스 자동삭제
        # selfHeal: true # 
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=background #하위 리소스부터 삭제
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2   #2배증가
        maxDuration: 3m
