apiVersion: apps/v1
kind: Deployment

metadata:
  name: api-deploy
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      app: commerce-api

  template:
    metadata:
      labels:
        app: commerce-api
      annotations:
        rollme: {{ .Values.api.rollme | quote }}
    spec:
      containers: 
      - name: api-container
        image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag | default "latest" }}"
        ports:
        - containerPort: {{ .Values.api.containerPort }}
        imagePullPolicy: {{ .Values.api.image.pullPolicy }}
        env:
          - name: SPRING_DATASOURCE_URL
            value: {{ .Values.api.env.datasource.url | quote }}
          - name: SPRING_DATASOURCE_USERNAME
            value: {{ .Values.api.env.datasource.username | quote }}
          - name: SPRING_DATASOURCE_PASSWORD
            value: {{ .Values.api.env.datasource.password | quote }}
        resources:
          requests:
            cpu: {{ .Values.api.resources.requests.cpu }}
            memory: {{ .Values.api.resources.requests.memory }}
          limits:
            cpu: {{ .Values.api.resources.limits.cpu }}
            memory: {{ .Values.api.resources.limits.memory }}


        livenessProbe:
          httpGet:
            path: {{ .Values.api.probes.path }}
            port: {{ .Values.api.probes.port }}
          initialDelaySeconds: {{ .Values.api.probes.liveness.initialDelaySeconds }}
          periodSeconds: {{ .Values.api.probes.liveness.periodSeconds }}
        readinessProbe:
          httpGet:
            path: {{ .Values.api.probes.path }}
            port: {{ .Values.api.probes.port }}
          initialDelaySeconds: {{ .Values.api.probes.readiness.initialDelaySeconds }}
          periodSeconds: {{ .Values.api.probes.readiness.periodSeconds }}

---
apiVersion: v1
kind: Service

metadata:
  name: api-svc
  labels:
    app: commerce-api
spec:
  type: {{ .Values.api.service.type }}
  selector:
    app: commerce-api  #deployment의 selector.matchLables.app 와 동일
  ports:
    - name: http
      protocol: {{ .Values.api.service.protocol }}
      port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.targetPort }}
    - name: metrics
      port: {{ .Values.api.service.metricsPort}}
      targetPort: {{ .Values.api.service.targetPort }}
        
